file_format: "1"
id: SplitLemon
name: SplitLemon
type: shield
rl: https://github.com/deltameh/zmk-config-SplitLemon
requires: [nice_nano_v2]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - SplitLemon_left
  - SplitLemon_right